//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLandByYarin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Deals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food_Deals()
        {
            this.Food_Deal_Details = new HashSet<Food_Deal_Details>();
        }
    
        public int Id { get; set; }
        public int Worker { get; set; }
        public int Costumer { get; set; }
        public int Price { get; set; }
    
        public virtual Costumers Costumers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food_Deal_Details> Food_Deal_Details { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
