//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLandByYarin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Deal
    {
        public int Id { get; set; }
        public int Worker { get; set; }
        public int Costemer { get; set; }
        public string Price { get; set; }
        public string Ticket_Type { get; set; }
        public int Movie { get; set; }
        public string Date { get; set; }
        public string Time_ofMovie { get; set; }
    
        public virtual Costumers Costumers { get; set; }
        public virtual Movies Movies { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
