//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLandByYarin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Deal_Details
    {
        public int Id { get; set; }
        public int DealID { get; set; }
        public int Ticket_Type { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public string Remarks { get; set; }
    
        public virtual Movie_Deal Movie_Deal { get; set; }
        public virtual ticket_type ticket_type1 { get; set; }
    }
}
