//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLandByYarin
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplies_type
    {
        public int Id { get; set; }
        public string food { get; set; }
        public string clean_metrial { get; set; }
        public string uniforms { get; set; }
    }
}
